name: Build Custom Android Client
on:
  repository_dispatch:
    types: [build-custom-client]

env:
  RUST_VERSION: "1.75"
  CARGO_NDK_VERSION: "3.1.2"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  NDK_VERSION: "r28c"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.7"

jobs:
  generate-bridge:
    if: github.event.client_payload.build_options.build_target_os == 'android'
    uses: ./.github/workflows/bridge.yml

  build-android:
    needs: [generate-bridge]
    if: github.event.client_payload.build_options.build_target_os == 'android'
    name: Build Branded Android Client (aarch64)
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake curl gcc-multilib git g++ g++-multilib libayatana-appindicator3-dev libasound2-dev libc6-dev libclang-dev libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libpam0g-dev libpulse-dev libva-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev libxfixes-dev llvm-dev nasm ninja-build openjdk-17-jdk-headless pkg-config tree wget

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch || 'main' }}
          submodules: recursive

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.ANDROID_FLUTTER_VERSION }}

      - name: Patch flutter
        run: |
          cd $(dirname $(dirname $(which flutter)))
          [[ "3.24.5" == ${{env.ANDROID_FLUTTER_VERSION}} ]] && git apply ${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: /opt/artifacts/vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        run: |
          if ! ./flutter/build_android_deps.sh "arm64-v8a"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              echo "======"
              cat "$_1"
              echo "======"
              echo ""
            done
            exit 1
          fi
        shell: bash

      - name: Restore bridge files
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rustdesk-lib-cache-android-custom
          key: aarch64-linux-android

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Pillow for Icon Generation
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Generate Custom Icons and Assets
        run: |
          echo "${{ github.event.client_payload.logo_png_base64 }}" > logo_base64.txt
          python make_icons.py logo_base64.txt "${{ github.event.client_payload.client_name }}"

      - name: Setup Custom Environment variables for oneKey.py
        shell: bash
        run: |
          echo "NEW_APP_NAME=${{ github.event.client_payload.client_name }}" >> $GITHUB_ENV
          echo "NEW_EXE_NAME=${{ github.event.client_payload.client_exe_name }}" >> $GITHUB_ENV
          echo "NEW_PREFIX=${{ github.event.client_payload.client_prefix }}" >> $GITHUB_ENV
          echo "NEW_IP=${{ github.event.client_payload.relay_host }}" >> $GITHUB_ENV
          echo "NEW_PUB_KEY=${{ github.event.client_payload.relay_key }}" >> $GITHUB_ENV
          echo "NEW_API_SERVER=${{ github.event.client_payload.api_server }}" >> $GITHUB_ENV
          echo "CUSTOM_TXT_BASE64=${{ github.event.client_payload.custom_txt_base64 }}" >> $GITHUB_ENV
          echo "APPLY_PATCHES=${{ github.event.client_payload.build_options.apply_patches }}" >> $GITHUB_ENV
          echo "ANDROID_PACKAGE_NAME=${{ github.event.client_payload.build_options.packageName }}" >> $GITHUB_ENV
          echo "BG_PNG_BASE64=${{ github.event.client_payload.bg_png_base64 }}" >> $GITHUB_ENV

      - name: Run Customize Script and Apply Patches
        run: |
          python oneKey.py

      - name: Build rustdesk lib
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          rustup target add aarch64-linux-android
          cargo install cargo-ndk --version ${{ env.CARGO_NDK_VERSION }} --locked
          ./flutter/ndk_arm64.sh
          mkdir -p ./flutter/android/app/src/main/jniLibs/arm64-v8a
          cp ./target/aarch64-linux-android/release/liblibrustdesk.so ./flutter/android/app/src/main/jniLibs/arm64-v8a/librustdesk.so

      - name: Build Custom Android Package
        shell: bash
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          export PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
          sed -i "s/org.gradle.jvmargs=-Xmx1024M/org.gradle.jvmargs=-Xmx2g/g" ./flutter/android/gradle.properties
          sed -i "s/signingConfigs.release/signingConfigs.debug/g" ./flutter/android/app/build.gradle
          
          mkdir -p ./flutter/android/app/src/main/jniLibs/arm64-v8a
          cp ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so ./flutter/android/app/src/main/jniLibs/arm64-v8a/
          cp ./target/aarch64-linux-android/release/liblibrustdesk.so ./flutter/android/app/src/main/jniLibs/arm64-v8a/librustdesk.so
          
          pushd flutter
          FORMAT="${{ github.event.client_payload.build_options.packageFormat }}"
          if [ "$FORMAT" = "aab" ]; then
            flutter build appbundle --release --target-platform android-arm64
            mv build/app/outputs/bundle/release/app-release.aab ../${{ github.event.client_payload.client_exe_name }}
          else
            flutter build apk --release --target-platform android-arm64 --split-per-abi
            mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ../${{ github.event.client_payload.client_exe_name }}
          fi
          popd

      - name: Zip finished custom client package
        run: |
          zip -r custom_client.zip ./${{ github.event.client_payload.client_exe_name }}

      - name: Upload Finished Custom Client Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.client_payload.client_guid }}-android
          path: ./custom_client.zip
